INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (274,'SIS:Kixi Agenda','APL001',0,'Kixi Agenda');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (275,'SIS:Kixi API','APL001',0,'Kixi API');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (276,'SIS:Kixi BKSQL','APL001',0,'Kixi BKSQL');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (277,'SIS:Kixi Cliente Web','APL001',0,'Kixi Cliente Web');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (278,'SIS:Kixi Cliente Mobile','APL001',0,'Kixi Cliente Mobile');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (279,'SIS:Kixi Facturação','APL001',0,'Kixi Facturação');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (280,'SIS:Kixi Loan','APL001',0,'Kixi Loan');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (281,'SIS:Kixi Pedidos','APL001',0,'Kixi Pedidos');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (282,'SIS:Kixi SMS','APL001',0,'Kixi SMS');
INSERT INTO public.objecto(id,objecto,id_tipo_objecto,ordem,apresentar) VALUES (283,'SIS:Kixi Utilitário','APL001',0,'Kixi Utilitário');