INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INACFE', 'FEC001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('ADSEHI', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GECOEQ', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GECOEQ', 'PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GECOEQ', 'PRO001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEFOEX', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEFOEX', 'PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('ADSOMA', 'DOC001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEPASE', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESOAR', 'PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESOAR', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEEXCE', 'CRE002');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INCAKV', 'PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDALSC', 'DES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INREUN', 'APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPPOAV', 'POU001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPPOEL', 'POU001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INOBME', 'OBJ001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESODA', 'DOC003');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESODA', 'POU001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESODA', 'DOC005');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESODA', 'DOC006');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GESODA', 'DOC007');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STSTSW', 'PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INREUN', 'APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INREUN', 'PES002');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('INREUN', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDALSC', 'DES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDDEPU', 'LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDDEPU', 'APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STALUT','PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STCRUT','PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STPRUT','PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STSTHW','EQU001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STSTHW','EQU002');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STSTHW','EQU003');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STSTHW','EQU004');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('STSTHW','EQU005');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEESCL','REL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEESCL','CRE001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEESCL','APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEESCL','POU001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('GEESCL','LUG001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDPASI','APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDPRDE','PRO001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDPRDE','APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('PDPRSI','APL001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('RHABVA','PRO001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('RHAULT','PES001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPACCA','CRE001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPACCA','CRE002');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPANCR','CRE002');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPANDE','CRE001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPANDE','CRE002');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPCMPC','PFK001');
INSERT INTO public.tipo_tipoobjecto(id_tipo, id_tipoobjecto) VALUES ('SPELRE','CRE002');